### ISSUE TITLE
Support for read data APIs

### ISSUE THREAD

**Issue by fcobb** [signalfx/signalfx-go#1]
Hello,

Excited to see this library get started, I am interested programmatically querying for metric data in go.
We are currently assessing using Signalflow via the websockets and the SSE APIs.

How likely is it that this library will support the read path for the APIs?

Thanks,
Fraser

**Comment by cory-signalfx** [comment]
Hey @fcobb! I'm glad you asked. We totally wanna add this. We're still shaking out some basic functionality here (as you can see) but it's definitely on the list. I'll add a TODO to the readme to make that obvious for future explorers!

**Comment by keitwb** [comment]
This has a basic SignalFlow client now from #7.  We haven't tagged a version yet and should definitely be considered early beta, but it should handle the basic use case of executing jobs and streaming data.  Please open separate issues if you have specific feature requests or find any bugs.  Hope that helps!

**Comment by keitwb** [comment]
Actually I guess some of the HTTP API client functionality is still missing to get metric/dimension metadata, so perhaps that aspect should be opened in a separate issue.
