### ISSUE TITLE
Radial missing min and max option for radial single value chart visualisation

### ISSUE THREAD

**Issue by milanilavsky** [signalfx/signalfx-go#129]
Hello,

wa want to use radial secondary visualisation for single value chart, but request fails with 400 - "Open ended range not allowed" because min and max values are missing. They could be set in UI which looks like this:
<img width="988" alt="Screen Shot 2021-07-21 at 14 40 54" src="https://user-images.githubusercontent.com/7854500/126431973-a46ef4e0-0ee7-4030-8fcf-d2ffa2964821.png">

Would it be possible to support these options, so we can generate radial chart? Or is there some other way we have overlooked?

**Comment by keitwb** [comment]
Hi, can you post the request you are doing right now?  We might need to update our models here to get some new fields but I want to make sure there isn't something missing from what you are trying so far.
