### ISSUE TITLE
AWS/WAFv2 is missing

### ISSUE THREAD

**Issue by spurge** [signalfx/signalfx-go#139]
We need to correlate traffic with metrics from AWS CloudFront, WAFv2, load balancers and service metrics. I tried implement this myself and deploy this with your Terraform provider, but got a 400 as this doesn't seem implemented in your backend.

AWS WAF is legacy and we need support for WAFv2 which has been available since Nov 2019.

https://github.com/spurge/signalfx-go/commit/e0d53c6f2bf05d3c5acef15a0345941eccf6c46d

**Comment by mmusik** [comment]
hi, a Splunker here. We've added the request to add WAFV2 metrics to our internal backlog; you're right it's not in the list of things supported out of the box. For now, you should be able to workaround that specifying WAFV2 as a custom namespace in the AWS integration (you can add any Cloudwatch namespace you want this way). In the API it looks like this:

```
{
	....
	"customNamespaceSyncRules": [
		{
			"namespace": "AWS/WAFV2",
			"filter": null,
			"defaultAction": null
		}
	],
	...
}

```

**Comment by spurge** [comment]
Thanks @mmusik, I'll try that!

**Comment by mmusik** [comment]
@spurge AWS/WAFV2 is enabled in our backend and was just added to the list of namespaces here as well https://github.com/signalfx/signalfx-go/pull/140/files
