### ISSUE TITLE
Allow http.Client to be injected

### ISSUE THREAD

**Issue by keitwb** [signalfx/signalfx-go#2]
To use this in the Smart Agent, we would need for several `http.Client` options to be tuneable.  A lot of API clients allow you to either override the `http.Client` instances used, either by a setter method or just making the `http.Client` field an exported memory of the client struct so it can be directly set.  This would probably be the most flexible approach compared to trying to pass through all of the options that `http.Client` has on it.  The Smart Agent's dimension property updater client uses [this option set](https://github.com/signalfx/signalfx-agent/blob/113d0d41b7caf5375595ed3bed2a94cfd6202c2a/internal/core/writer/properties/client.go#L69).

**Comment by cory-signalfx** [comment]
On it!

**Comment by cory-signalfx** [comment]
Done in #3
