### ISSUE TITLE
Colors, colors and colors

### ISSUE THREAD

**Issue by doctornkz** [signalfx/signalfx-go#26]
Hi contributors, I hope that issue can't break your Monday motivation!
Right now I am working hard on my `signalFX->terraform configuration` cli-exporter. And I am stucked with two problems:
1. Undocumented color's palette. I am spending a lot time with mapping Palette.Id and real color. The most fun I received from pink, purple, magenta, iris - I can't catch the difference!
2. Colorization is not consistent. Some stuff has 16 colors palette, other - 21 colors, sometimes we are using int32 number for color mapping, sometimes - hex #666666.
How we can improve that, friends?

**Comment by cory-signalfx** [comment]
A great question! At present, a lot of this is encoded into the Terraform provider. We could definitely move it here. I'll say that this is lower priority to me than some other Terraform provider features, though.

One more question: cli exporter? As of last week the provider now supports `terraform import` which means you can pretty easily import and get the configuration for any asset. Does that suit your needs? There is also [signalfx-to-terraform](https://github.com/signalfx/signalfx-to-terraform) which is rather rough…

**Comment by doctornkz** [comment]
1. About colors - Got it. Will politely wait improvements.
2. I will see on `terraform import` but looks it can't import signalFX json _as is_. 
Jinja-template programming hard way for our users. Also I prefer to use native upstream libraries from `signalfx/terraform` instead json/string/dict manipulation with python. But I agree - one more `bicycle reinvention` from my side )

**Comment by cory-signalfx** [comment]
1. Ok! ;)
2. It definitely can't import JSON as it. By all means continue!

**Comment by doctornkz** [comment]
Yeah! I found 4th variant - 
```
histogram_options - (Optional) Only used when plot_type is "Histogram". Histogram specific options.
color_theme - (Optional) Color to use : gray, blue, azure, navy, brown, orange, yellow, iris, magenta, pink, purple, violet, lilac, emerald, green, aquamarine, red, gold, greenyellow, chartreuse, jade
```
seems, we have typo here?

**Comment by doctornkz** [comment]
Found the really funny stuff:
*int:
https://github.com/signalfx/signalfx-go/blob/master/chart/model_event_publish_label_options.go#L6
*int32
https://github.com/signalfx/signalfx-go/blob/master/chart/model_publish_label_options.go#L18
but semantically it should be the same )

**Comment by doctornkz** [comment]
@cory-signalfx , jfyi: https://github.com/doctornkz/signalfx2terraform , we are using this tool to export data from API.

**Comment by atoulme** [comment]
Yes, roughly 5 years made it seem to me like it was time to close the issue. We can open a Splunk idea (ideas.splunk.com) to follow up if you'd like.

**Comment by doctornkz-intelas** [comment]
No, thank you @atoulme, I am not with signalfx/splunk tech stack anymore. But your action reminded me of all @cory-signalfx efforts. Wish you, folks, all the best.
