### ISSUE TITLE
Notifications [detector]

### ISSUE THREAD

**Issue by doctornkz** [signalfx/signalfx-go#27]
We have a different meaning of `notification` field in detector's code and from terraform-provider documentation.
[Documentation](https://github.com/signalfx/terraform-provider-signalfx/blob/master/website/docs/r/detector.html.markdown): 
```
notifications - (Optional) List of strings specifying where notifications will be sent when an incident occurs. 
```
[Code](https://github.com/signalfx/signalfx-go/blob/master/detector/model_rule.go):
```
Notifications []map[string]interface{} `json:"notifications,omitempty"`
```
So, what do we have `List of strings` or `List of Maps` ? 
List of strings more preferable, cos more easier to process it with `cty` library.

**Comment by doctornkz** [comment]
Hmm. I am wrong 
API gives me 
```
    "notifications" : [ {
      "type" : "Team",
      "team" : "****"
    } ],
```
It's `List of Maps`, definitely

**Comment by cory-signalfx** [comment]
It's definitely a list of maps. The Terraform provider — for reasons that predate me — uses this string format. Soon, in [this PR](https://github.com/signalfx/terraform-provider-signalfx/pull/78) the Terraform provider will use this librfary under the hood instead of it's current `map[string]interface{}`.

**Comment by doctornkz** [comment]
Thank you, friend. Right now it seems impossible to create detector with Map objects:
```
Error: signalfx_detector.sfx-D-*****: rule.0.notifications.2 must be a single value, not a map
```
I tried that section inside `tf` config file :
```
    notifications = [{ team = "****", type = "Team" }, { email = "*******@olx.com", type = "Email" }, { channel = "#alerts_critical", credentialId = "****", type = "Slack" }]
  }
}
```
8(

**Comment by cory-signalfx** [comment]
Yes, that's because the string form is used in Terraform! [Here are the docs for that](https://github.com/signalfx/terraform-provider-signalfx/blob/master/website/docs/r/detector.html.markdown#notification-format).

**Comment by cory-signalfx** [comment]
You'll want something like this on the Terraform side:

```
rule {
        …
        notifications = ["Team,***", "Email,*******@olx.com"]
    }
```

But on the client lib side, the aforementioned list of maps is the way.

**Comment by doctornkz** [comment]
No problem friends, I gonna implement wrapper around signalFX's notification object. Thank you for your help and time!

**Comment by cory-signalfx** [comment]
:bow
