### ISSUE TITLE
`Nil pointer dereference` related

### ISSUE THREAD

**Issue by doctornkz** [signalfx/signalfx-go#43]
It's not a blocker, just possible improvement.
Sometimes I catch nil pointer due fields are not set. 
As instance: 
`disable_sampling` (bool type) in chart structure.
I can't check is set value or not. And I forced to skip parsing that field. 
With `max_delay` (*int32 type) I can check value against `nil` (thank you for improvements, btw)
Additionally notice nil pointer is uncaughtable exception, it impossible to 'wrapperize' that.
Maybe I am doing something wrong, please explain me.

Example
1. Config file processor:
```
	// Nil type is possible, `disable_sampling` commented.
	// chartBody.SetAttributeValue("disable_sampling", disableSamplingProc(chart))
	chartBody.SetAttributeValue("max_delay", cty.NumberIntVal(maxDelayProc(chart)))
	return chartBody
```
2. Wrapper for max_delay (works fine):
```
func maxDelayProc(chart *chart.Chart) int64 {
	if chart.Options.ProgramOptions.MaxDelay == nil {
		return 0
	}
	return int64(*chart.Options.ProgramOptions.MaxDelay / 1000) // Convert to sec
}
```
3. Wrapper for disable_sampling (exception):
```
func disableSamplingProc(chart *chart.Chart) cty.Value {
	return cty.BoolVal(chart.Options.ProgramOptions.DisableSampling) // Nil is possible here!
}
```

**Comment by doctornkz** [comment]
I need to investigate more carefully that. Sorry for annoying.

**Comment by cory-signalfx** [comment]
Not annoying at all!

In all of these cases you should be checking if `ProgramOptions` is `nil`, right? These fields are not guaranteed to be returned in the response, so you'll to wrap reads or writes of `DisableSampling` and other members with check of `if chart.Options != nil && chart.Options.ProgramOptions != nil`.

**Comment by doctornkz** [comment]
Ah, ok. Thank you, Cory!

**Comment by doctornkz** [comment]
`if chart.Options != nil || chart.Options.ProgramOptions != nil` < that approach is more correct, I think

**Comment by cory-signalfx** [comment]
ah, yes, otherwise it would evalulate the expression after the `&&`
