### ISSUE TITLE
Any plans for releasing v1?

### ISSUE THREAD

**Issue by noliva** [signalfx/signalfx-go#5]
Hello, thank you so much for this library, we are looking at using it but was wondering when will it be mature or what is the current status of this library.

**Comment by cory-signalfx** [comment]
Hey @noliva! Thanks for reaching out, I'm glad you're looking into it.

I'm currently iterating on some related code that can help me generate the request/response bodies that this library uses. The goal is to avoid the universal problem of keeping yet another library up to date.

That said, I don't want to block you too hard. Do you have a specific part of the library that is most useful to you? Perhaps I can work on getting that production reader sooner?

As it stands this is still very much a moving target.

**Comment by cory-signalfx** [comment]
Hey @noliva,

I think this library is pretty stable for some of the core nouns (dashboards, charts, etc) but is still growing functionality. I think the obvious problem for me is what 1.0 means, short of full-API functionality.

As it stands I think I'll tag it later this week and call this ticket done for now. 1.0 seems like a fine name if I don't ascribe too much value to it. :)

**Comment by cory-signalfx** [comment]
Done and tagged! There's still more to add, of course, but we'll do that in continued iterations. Please file tickets for anything you need!
