### ISSUE TITLE
missing endpoints: detector events and incidents

### ISSUE THREAD

**Issue by yiwen-stripe** [signalfx/signalfx-go#67]
The two endpoints:
* `/detector/{id}/events`
* `/detector/{id}/incidents`

Thanks!

**Comment by cory-signalfx** [comment]
Will do, probably tomorrowish!

**Comment by cory-signalfx** [comment]
Hey @yiwen-stripe, how's this look? If you can try it out with a `go get` or something that'd be cool. If not I'll just merge it Tuesday!

**Comment by yiwen-stripe** [comment]
Hey @cory-signalfx,

Thanks for the quick turnaround! I tested the events function and it seemed to be working. I didn't have any incidents on hand that I could query but it did return an empty list for my detector without any incidents

Will there be query params (events: from, to, offset, limit) (incidents: offset, limit) at some point?

**Comment by cory-signalfx** [comment]
Oops! How'd I forget that? Will do that today.

**Comment by cory-signalfx** [comment]
There we go @yiwen-stripe, that should do it!

I'll merge this later today if you have no objections.

**Comment by cory-signalfx** [comment]
Tagged as v1.6.17, lemme know if that's working now @yiwen-stripe!

**Comment by yiwen-stripe** [comment]
did a quick test, looks like it's working! thanks a lot!
