### ISSUE TITLE
adding request context

### ISSUE THREAD

**Issue by yiwen-stripe** [signalfx/signalfx-go#88]
We'd like to add tracing to some of our requests coming from this library. Unfortunately, it seems that none of the endpoints we are using utilize context (detector api), which means we can't pass that information through. Can we add some contexts to the API (or perhaps add new functions that utilize context)?

**Comment by cory-signalfx** [comment]
Yeah, that seems reasonable! I'm not sure how quickly I can get to it, but keep an eye out for a PR!

**Comment by choo-stripe** [comment]
thanks cory!

**Comment by cory-signalfx** [comment]
Hey @yiwen-stripe and @choo-stripe! Could you volunteer some places where this would be helpful to you in the near term?  Obviously I could add it as a parameter, but I imagine you want either some form of tracing or cancelation here?

**Comment by choo-stripe** [comment]
Howdy! Recently I used https://godoc.org/github.com/signalfx/signalfx-go#Client.GetDetectorIncidents and was scratching my head as to where the `WithContext` variant was. I didn't PR it because I assumed I would've had to add for all functions, which I didn't have time for. I wonder if we could codemod this.

Not sure if Yiwen has more to add

**Comment by cory-signalfx** [comment]
But merely adding the context doesn't really do anything, right? Unless I look into it for cancelation or do some tracing stuff, this is a null op?

**Comment by choo-stripe** [comment]
Right - that was it - I was hoping to add context to the request here: https://github.com/signalfx/signalfx-go/blob/ceee8d2570d5842692c54cb920ed88a76db2586b/client.go#L93

Basically using https://golang.org/pkg/net/http/#NewRequestWithContext

We have generic tracing for all reqs, and enforce that egress is traced. We do this by adding context to the requests and shimming the `Dial` function in the `http.Client`.

I was able to hack around this, but adding contexts to requests seems like a fairly standard feature these days.

**Comment by cory-signalfx** [comment]
Ah, ok. That makes sense. Thanks for clarifying.

**Comment by cory-signalfx** [comment]
Done!

**Comment by choo-stripe** [comment]
You're an absolute wizard. Pls come back soon.

**Comment by cory-signalfx** [comment]
It was your idea, not mine!

lol :)
